name: kitematic
summary: Kitematic is a simple application for managing Docker containers on Mac,Linux and Windows.
description: 
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  kitematic:
    command: kitematic
    plugs:
      - network

parts:
  kitematic:
    plugin: 
    source: https://github.com/docker/kitematic.git
    source-type: git
    override-pull: |
      git clone https://github.com/docker/kitematic.git src/github.com/docker/kitematic
       cd src/github.com/docker/kitematic
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/docker/kitematic
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/docker/kitematic/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/docker/kitematic/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/kitematic
    build-snaps:
      - 
    build-packages:
      - git
      - sed
